name: Implementing Github Actions
on: [push]
jobs:
  Implementing-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install wget unzip -y
      - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo apt install ./google-chrome-stable_current_amd64.deb && sudo rm google-chrome-stable_current_amd64.deb
      - run: wget https://github.com/gagankeshav/homes.co.nz_tests/archive/refs/heads/GitHubActionsTest.zip && unzip GitHubActionsTest.zip && sudo rm GitHubActionsTest.zip
      - run: cd homes.co.nz_tests-GitHubActionsTest/ && ls && pwd && chmod +x run_tests.sh && sudo ./run_tests.sh staging
