name: Implementing Github Actions
on: [push]
jobs:
  Implementing-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: sudo gem install selenium-webdriver
      - run: sudo apt install wget unzip -y
      - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: sudo apt install ./google-chrome-stable_current_amd64.deb
      - run: sudo rm google-chrome-stable_current_amd64.deb
      - run: wget https://github.com/gagankeshav/homes.co.nz_tests/archive/master.zip
      - run: unzip master.zip
      - run: sudo rm master.zip
      - run: sh test_specs.sh staging
